<?php

namespace Container7UXK17l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pAfMIUC.App\Controller\ActualiteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pAfMIUC.App\\Controller\\ActualiteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actualite' => ['privates', '.errored..service_locator.pAfMIUC.App\\Entity\\Actualite', NULL, 'Cannot autowire service ".service_locator.pAfMIUC": it needs an instance of "App\\Entity\\Actualite" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'actualite' => 'App\\Entity\\Actualite',
        ]))->withContext('App\\Controller\\ActualiteController::show()', $container);
    }
}
