<?php

namespace Container7UXK17l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XipZ3s2.App\Controller\ActualiteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XipZ3s2.App\\Controller\\ActualiteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actualiteRepository' => ['privates', 'App\\Repository\\ActualiteRepository', 'getActualiteRepositoryService', true],
        ], [
            'actualiteRepository' => 'App\\Repository\\ActualiteRepository',
        ]))->withContext('App\\Controller\\ActualiteController::index()', $container);
    }
}
