<?php

namespace Container7UXK17l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k0gGN0a.App\Entity\Actualite' shared service.
     *
     * @return \App\Entity\Actualite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.k0gGN0a": it needs an instance of "App\\Entity\\Actualite" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
