<?php

namespace Container7UXK17l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ngkPSs6.App\Controller\CommentaireController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ngkPSs6'] ?? $container->load('get_ServiceLocator_NgkPSs6Service'));

        if (isset($container->privates['.service_locator.ngkPSs6.App\\Controller\\CommentaireController::edit()'])) {
            return $container->privates['.service_locator.ngkPSs6.App\\Controller\\CommentaireController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\CommentaireController::edit()', $container);

        if (isset($container->privates['.service_locator.ngkPSs6.App\\Controller\\CommentaireController::edit()'])) {
            return $container->privates['.service_locator.ngkPSs6.App\\Controller\\CommentaireController::edit()'];
        }

        return $container->privates['.service_locator.ngkPSs6.App\\Controller\\CommentaireController::edit()'] = $instance;
    }
}
