<?php

namespace Container7UXK17l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k0gGN0a.App\Controller\CommentaireController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actualite' => ['privates', '.errored..service_locator.k0gGN0a.App\\Entity\\Actualite', NULL, 'Cannot autowire service ".service_locator.k0gGN0a": it needs an instance of "App\\Entity\\Actualite" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'actualite' => 'App\\Entity\\Actualite',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CommentaireController::new()', $container);

        if (isset($container->privates['.service_locator.k0gGN0a.App\\Controller\\CommentaireController::new()'])) {
            return $container->privates['.service_locator.k0gGN0a.App\\Controller\\CommentaireController::new()'];
        }

        return $container->privates['.service_locator.k0gGN0a.App\\Controller\\CommentaireController::new()'] = $instance;
    }
}
