<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Actualite extends \App\Entity\Actualite implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null, 16],
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'commentaires' => [parent::class, 'commentaires', null, 16],
        'contenu' => [parent::class, 'contenu', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
