<?php

namespace ContainerHjtC76w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignalerCommentaireControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3BoFVFw.App\Controller\SignalerCommentaireController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.3BoFVFw'] ?? $container->load('get_ServiceLocator_3BoFVFwService'));

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\SignalerCommentaireController::new()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\SignalerCommentaireController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\SignalerCommentaireController::new()', $container);

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\SignalerCommentaireController::new()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\SignalerCommentaireController::new()'];
        }

        return $container->privates['.service_locator.3BoFVFw.App\\Controller\\SignalerCommentaireController::new()'] = $instance;
    }
}
