<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjtC76w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjtC76w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHjtC76w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHjtC76w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHjtC76w\App_KernelDevDebugContainer([
    'container.build_hash' => 'HjtC76w',
    'container.build_id' => '533b83f3',
    'container.build_time' => 1770299975,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjtC76w');
